services:
  mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: admin
      MYSQL_USER: User
      MYSQL_PASSWORD: test
    volumes:
      - ./db/ :/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

  php-7.4:
    image: arthurelinux/php74apache
    ports:
      - 8080:80
    volumes:
      - ./html/Primeiro Projeto:/var/www/html
      - ./apache/modelo.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./log/apache2:/var/log/apache2

    depends_on:
      - mysql
      - phpmyadmin